# Generated by Django 2.1.7 on 2019-02-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_task_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_taker',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_done',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_taken',
            field=models.DateTimeField(),
        ),
    ]
