# Generated by Django 2.1.7 on 2019-02-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190214_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_done',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_taken',
            field=models.DateTimeField(blank=True),
        ),
    ]
