# Generated by Django 2.1.7 on 2019-02-14 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20190214_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
